name: Go

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Build the Ouhi-sama program
        run: go build -v -o bin/ouhisama cmd/ouhisama/ouhisama.go
      - name: Save the Ouhi-sama program
        run : |
            git config --local user.name "GitHub Actions"
            git config --local user.email "actions@github.com"
            git add bin/ouhisama
            git commit -m "Build the Ouhi-sama program"
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
