name: Go

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'
      - name: Build for Ouhissama (${{ matrix.os }} ${{ matrix.arch }})
        run: |
          mkdir -p bin

          EXT=""
          if [ "${{ matrix.os }}" == "windows" ]; then EXT=".exe"; fi
          OUTPUT="ouhisama-${{ matrix.os }}-${{ matrix.arch }}${EXT}"

          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/$OUTPUT cmd/ouhisama/ouhisama.go
      - name: Check for changes
        id: check
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            echo "::set-output name=changes::false"
          else
            echo "Changes detected"
            echo "::set-output name=changes::true"
          fi
      - name: Save the built Ouhi-sama programs
        if: steps.check.outputs.changes == 'true'
        run : |
            git config --local user.name "GitHub Actions"
            git config --local user.email "actions@github.com"
            git add bin/ouhisama
            git commit -m "Build the Ouhi-sama program"
            git push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
